# Generated by Django 3.1 on 2021-03-17 11:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('pdf', models.FileField(upload_to='pdf/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Patner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, upload_to='')),
                ('external_url', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', multiselectfield.db.fields.MultiSelectField(choices=[('ALL', 'ALL'), ('AGRICULTURE', 'AGRICULTURE'), ('TRAINING', 'TRAINING'), ('TECHNOLOGY', 'TECHNOLOGY')], default='ALL', max_length=120)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, default=None, upload_to='')),
                ('benefitiary', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('point_of_contact', models.TextField()),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media_pics/%Y/%m/%d')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.project')),
            ],
        ),
    ]
