# Generated by Django 3.1 on 2021-03-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_adverts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adverts',
            new_name='Advert',
        ),
    ]
